spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    queue: myqueue
  datasource:
    url: jdbc:h2:mem:messages
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl.auto: create
  h2:
    console:
      enabled: true
